runtime: python27
api_version: 1
threadsafe: yes

builtins:
- remote_api: on
- deferred: on

handlers:

- url: /docs/.*
  script: main.app
  secure: always
  login: admin

- url: .*
  script: main.app
  secure: always

libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: "2.6"
